<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Pingie</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <AndroidSdkDirectory>/home/bendzsi/Android/Sdk</AndroidSdkDirectory>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <MauiEnableIOS>false</MauiEnableIOS>
    <MauiEnableMacCatalyst>false</MauiEnableMacCatalyst>
    <MauiVersion>9.0.100</MauiVersion>
    <MauiEnableWindows>false</MauiEnableWindows>
    <MauiEnableTizen>false</MauiEnableTizen>
  </PropertyGroup>
  <ItemGroup>
    <MauiImage Include="Resources\Splash\splash.svg" />
    <MauiImage Include="Resources\Images\*" />
    <MauiFont Include="Resources\Fonts\*" />
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
    <None Remove="Resources\Images\Icons\backarrow.svg" />
    <EmbeddedResource Include="Resources\Images\Icons\backarrow.svg" />
    <None Remove="Resources\Images\Icons\plus.svg" />
    <EmbeddedResource Include="Resources\Images\Icons\plus.svg" />
    <None Remove="Resources\Images\Icons\exclamation.svg" />
    <EmbeddedResource Include="Resources\Images\Icons\exclamation.svg" />
    <None Remove="Resources\Images\Icons\downarrowselector.svg" />
    <EmbeddedResource Include="Resources\Images\Icons\downarrowselector.svg" />
    <None Remove="Resources\Images\Icons\backarrowselector.svg" />
    <EmbeddedResource Include="Resources\Images\Icons\backarrowselector.svg" />
    <None Remove="Resources\Images\Icons\logs.svg" />
    <EmbeddedResource Include="Resources\Images\Icons\logs.svg" />
    <None Remove="Resources\Images\Icons\edit.svg" />
    <EmbeddedResource Include="Resources\Images\Icons\edit.svg" />
    <None Remove="Resources\Images\Icons\trash.svg" />
    <EmbeddedResource Include="Resources\Images\Icons\trash.svg" />
    <None Remove="Resources\Images\Icons\resume.svg" />
    <EmbeddedResource Include="Resources\Images\Icons\resume.svg" />
    <None Remove="Resources\Images\Icons\pause.svg" />
    <EmbeddedResource Include="Resources\Images\Icons\pause.svg" />
    <None Remove="Resources\Images\Icons\share.svg" />
    <EmbeddedResource Include="Resources\Images\Icons\share.svg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Maui" Version="12.2.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.100" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.5" />
    <PackageReference Include="Mopups.Maui" Version="1.0.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="3.119.1" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageReference Include="Svg.Skia" Version="3.2.1" />
  </ItemGroup>
  <ItemGroup>
    <MauiXaml Update="View\MainPage.xaml">
      <SubType>Designer</SubType>
    </MauiXaml>
    <MauiXaml Update="Views\Pages\MainPage.xaml">
      <SubType>Designer</SubType>
    </MauiXaml>
    <MauiXaml Update="Views\Pages\PingableLogPage.xaml">
      <SubType>Designer</SubType>
    </MauiXaml>
    <MauiXaml Update="Views\Pages\DeviceDetailPage.xaml">
      <SubType>Designer</SubType>
    </MauiXaml>
    <MauiXaml Update="Views\PopUps\MainFlyoutSelectionBar.xaml">
      <SubType>Designer</SubType>
    </MauiXaml>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="View\MainPage.xaml.cs">
      <DependentUpon>MainPage.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\MainPage.xaml.cs">
      <DependentUpon>MainPage.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\PingableLogPage.xaml.cs">
      <DependentUpon>PingableLogPage.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\DeviceDetailPage.xaml.cs">
      <DependentUpon>DevicePage.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\PopUps\MainFlyoutSelectionBar.xaml.cs">
      <DependentUpon>MainFlyoutSelectionBar.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Data\Data.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
      <MauiIcon Include="Resources\AppIcon\pingieiconfg.svg" Color="#FFad1a5e"/>
  </ItemGroup>
</Project>

